import { AlertTriangle, BookOpen, CheckCircle2, Code2, Lightbulb } from 'lucide-react';

const profiles = {
  'estructuras-de-datos': ['Data Structures', 'A data structure is a disciplined way to store, connect, and access information so a program can perform its important operations efficiently.', ['Data','The values and relationships a program needs'], ['Organization','Indices, links, keys, or levels locate the data'], ['Operations','Search, insert, update, delete, and traverse'], 'Choose a structure from the operations and constraints of the problem, not from its name.', ['Separate the ADT contract from its implementation','Compare time and additional memory','Preserve the invariant after every change','Test empty, single-value, and large cases']],
  'complejidad-algoritmica': ['Algorithmic Complexity', 'Algorithmic complexity describes how time and additional memory grow with input size n. It compares scalability independently of a particular computer.', ['Input size n','The quantity that grows in the problem'], ['Time','How many relevant operations are executed'], ['Space','How much additional memory is required'], 'Keep the dominant growth term and state whether you are analyzing best, average, or worst case.', ['Define what n represents','Count the active operation','Distinguish O, Ω, and Θ','Analyze time and space separately']],
  'programacion-orientada-objetos': ['Object-Oriented Programming', 'OOP models a program through objects that combine state, behavior, and identity. A class defines the model; an object is a concrete instance created from it.', ['Class','The definition of attributes and methods'], ['Object','A real instance with its own identity and state'], ['Responsibility','The behavior one object must protect'], 'A class is the blueprint; each object built from it exists separately and stores its own values.', ['Protect state with encapsulation','Prefer clear responsibilities','Use inheritance only for a real is-a relationship','Use composition to connect collaborating objects']],
  'variables-tipos-operadores': ['Variables, Types, and Operators', 'A variable is a named place that stores a value. Its type determines which values are valid and which operations may be applied.', ['Type','What kind of value may be stored'], ['Variable','A meaningful name for a value'], ['Expression','Values and operators that produce a result'], 'The type explains what may be stored; the name explains why the value exists.', ['Initialize local variables before use','Use equals for String content','Check integer division','Use parentheses when precedence is unclear']],
  'condiciones-ciclos': ['Conditions and Loops', 'Conditions choose which branch runs; loops repeat instructions while a condition remains true. Java never enters every branch automatically.', ['if','Runs one branch when its condition is true'], ['for','A counted repetition with an update'], ['while','Repeats while a condition remains true'], 'A loop must change the state used by its condition so that it can eventually terminate.', ['Do not confuse = with ==','Use index < length','Trace the control variable','Explain why the loop stops']],
  'metodos-parametros': ['Methods and Parameters', 'A method groups one focused operation. Its signature communicates the name, parameters, and return type to callers.', ['Parameters','Input variables received by the method'], ['Body','The instructions for one responsibility'], ['Return','The result sent back to the caller'], 'A small method should be explainable with one short sentence.', ['Validate parameters','Keep one responsibility','Return every required path','Distinguish arguments from parameters']],
  'punteros-referencias': ['Pointers and References', 'Pointers and references provide indirect access to data. A pointer may expose a memory address; a managed reference identifies an object without raw address arithmetic.', ['Address','A location in memory'], ['Pointer','An explicit value that stores an address'], ['Reference','A managed link to an object'], 'The link is not the object: it is the information used to reach that object.', ['Check null before following a link','Track aliases that share an object','Preserve next before deletion','Repair every affected link']],
  'manejo-memoria-java': ['Memory Management in Java', 'Method frames and local variables belong to active calls, while arrays and objects created with new live on the heap. Unreachable objects may be reclaimed automatically.', ['Stack','Active method calls and local state'], ['Heap','Objects and arrays'], ['Garbage collector','Reclaims unreachable objects'], 'Automatic memory reclamation does not close files or fix unnecessary retained references.', ['Keep ownership clear','Release unnecessary references','Close external resources','Limit uncontrolled recursion']],
  'recursividad-fundamentos': ['Recursion Fundamentals', 'A recursive method solves a problem by calling itself with a smaller instance. Each call waits on the call stack until its child returns.', ['Base case','Stops without another call'], ['Recursive case','Moves toward a smaller problem'], ['Return path','Combines results while calls finish'], 'Every recursive call must move closer to a reachable base case.', ['Write the base case first','Prove input becomes smaller','Draw the call tree','Track results while returning']],
  'tipos-datos-abstractos': ['Abstract Data Types (ADT)', 'An ADT defines observable operations and rules without requiring one particular internal representation.', ['Contract','What the structure promises'], ['Implementation','How the contract is built'], ['Invariant','A rule every operation preserves'], 'The ADT says what users can observe; the data structure says how that promise is fulfilled.', ['List public operations','Define invalid cases','Hide representation details','Compare possible implementations']],
  'genericos-java': ['Generics in Java', 'Generics let one class or method work safely with several reference types while preserving compiler checks.', ['T','A type parameter chosen by the caller'], ['Type safety','Invalid element types fail at compilation'], ['Reuse','One structure supports many types'], 'Generics provide reusable code without giving up type safety.', ['Avoid raw types','Use bounds only when needed','Remember that containers are invariant','Use wrapper types for primitives']],
  'errores-excepciones': ['Errors and Exceptions', 'Validation prevents known invalid operations; exceptions report abnormal situations and preserve information about their cause.', ['Validation','Checks assumptions before mutation'], ['throw','Reports a meaningful failure'], ['catch','Handles a failure where recovery is possible'], 'An exception should explain a failure, not hide it.', ['Do not catch everything blindly','Preserve the original cause','Keep state valid after failure','Use try-with-resources']],
  'comparacion-ordenamiento-objetos': ['Comparing and Sorting Objects', 'Equality asks whether two objects represent the same value; ordering asks which one should come first.', ['==','Object identity'], ['equals','Logical content equality'], ['Comparator','An external ordering rule'], 'Equal objects must have equal hash codes, but unequal objects may still collide.', ['Keep equals and hashCode consistent','Use compareTo for natural order','Use Comparator for alternatives','Avoid subtraction overflow']],
  'diseno-representacion-algoritmos': ['Algorithm Design and Representation', 'Algorithm design transforms a problem into finite and precise steps before language syntax is considered.', ['Input','Data and assumptions received'], ['Process','Ordered decisions and repetitions'], ['Output','The required result and guarantees'], 'A precise algorithm can be followed by another person without guessing.', ['Write examples first','State constraints','Use pseudocode or diagrams','Perform a desk check']],
  'correctitud-algoritmos': ['Algorithm Correctness', 'Correctness explains why an algorithm returns the required result for every valid input and why it terminates.', ['Precondition','What must be true before execution'], ['Invariant','What remains true during execution'], ['Postcondition','What is guaranteed afterward'], 'Tests can reveal errors; a proof explains why all valid cases work.', ['State assumptions','Prove invariant initialization','Prove preservation','Prove termination']],
  'pruebas-depuracion': ['Testing and Debugging', 'Testing deliberately searches for failures; debugging follows a failure back to the first incorrect program state.', ['Test case','Input, action, and expected result'], ['Trace','State changes over time'], ['Assertion','An executable expected property'], 'The visible symptom may happen long after the first incorrect state.', ['Cover boundary cases','Reduce to a small reproduction','Compare expected and actual state','Keep a regression test']],
  'fundamentos-backtracking': ['Backtracking Fundamentals', 'Backtracking chooses a candidate, validates it, explores recursively, and undoes the choice when the branch cannot produce a solution.', ['Choose','Temporarily add one candidate'], ['Check','Reject invalid partial states'], ['Undo','Restore state before the next candidate'], 'The undo step is what distinguishes backtracking from plain recursive enumeration.', ['Define a complete solution','Write isSafe','Prune invalid branches','Restore state exactly']],
  'fundamentos-busqueda-binaria': ['Binary Search Fundamentals', 'Binary search locates a target by discarding half of a sorted interval after each comparison.', ['Sorted input','Required for safe elimination'], ['Middle','The comparison position'], ['Interval','Candidates between left and right'], 'Every comparison must strictly reduce the active interval.', ['Confirm sorting','Use right = n - 1','Compute a safe midpoint','Test missing values']],
  'fundamentos-divide-venceras': ['Divide and Conquer Fundamentals', 'Divide and Conquer splits a problem into smaller independent subproblems, solves them, and combines their answers.', ['Divide','Create smaller subproblems'], ['Conquer','Solve each part recursively'], ['Combine','Build the final answer'], 'Subproblems must become smaller and together cover the original problem.', ['Define a direct base case','Prove size decreases','Preserve all input data','Analyze combination cost']],
  'programacion-dinamica': ['Dynamic Programming Fundamentals', 'Dynamic Programming stores answers to overlapping subproblems so each one is solved only once.', ['State','A precise subproblem'], ['Recurrence','How smaller states build a result'], ['Storage','Memoization or tabulation'], 'Dynamic Programming trades additional memory for avoiding repeated computation.', ['Define state in one sentence','Write base states','Choose dependency order','Return the requested final state']],
};

const codeExamples = {
  'variables-tipos-operadores':'int age = 18;\nage = age + 1;', 'condiciones-ciclos':'for (int i = 0; i < values.length; i++) {\n    System.out.println(values[i]);\n}',
  'metodos-parametros':'static int add(int a, int b) {\n    return a + b;\n}', 'recursividad-fundamentos':'static int factorial(int n) {\n    if (n <= 1) return 1;\n    return n * factorial(n - 1);\n}',
  'genericos-java':'class Box<T> {\n    T value;\n    T get() { return value; }\n}', 'fundamentos-busqueda-binaria':'while (left <= right) {\n    int middle = left + (right - left) / 2;\n    // Compare and discard one half\n}',
  'fundamentos-backtracking':'choose(candidate);\nif (solve(next)) return true;\nundo(candidate);', 'programacion-dinamica':'int[] dp = new int[n + 1];\ndp[0] = baseCase;\n// Build each state once',
};

export default function EnglishFoundationLesson({ algorithm }) {
  const p = profiles[algorithm.id] ?? [algorithm.name, algorithm.description, ['Concept','The central idea'], ['Rule','What remains valid'], ['Practice','How to apply it'], 'Understand the rule before memorizing syntax.', ['Define inputs and outputs','Follow state changes','Test boundary cases','Explain the result']];
  const concepts = [p[2], p[3], p[4]];
  const code = codeExamples[algorithm.id];
  const mistakes = ['Skipping the input assumptions or required conditions','Changing state without preserving the central rule','Testing only one normal example','Memorizing syntax without tracing how values change'];
  return <section className="complexity-lesson foundation-lesson" data-foundation-lesson={algorithm.id}>
    <article className="complexity-intro-card foundation-intro-card"><span className="lesson-kicker">01 · CENTRAL IDEA</span><h2>{p[0]}</h2><p>{p[1]}</p><div className="complexity-foundations foundation-key-grid">{concepts.map(([term,text])=><div key={term}><strong>{term}</strong><span>Core concept</span><p>{text}</p></div>)}</div></article>
    <div className="foundation-section-grid">
      <article><span className="lesson-kicker">02 · CONCEPT</span><h3>How it works</h3><p>{p[1]} The algorithm or program changes its state only through operations that preserve the stated rules.</p><ul><li>Identify the information that enters the process.</li><li>Follow each decision and state change in order.</li><li>Check the condition that finishes the process.</li></ul></article>
      <article><span className="lesson-kicker">03 · CONCEPT</span><h3>Why it matters</h3><p>This foundation helps explain not only what the program does, but why each step is valid and how the same reasoning can be reused in a new problem.</p></article>
      <article><span className="lesson-kicker">04 · CONCEPT</span><h3>How to reason about it</h3><p>Separate inputs, internal state, operations, and outputs. Then test a small example by hand and record every change before writing more code.</p>{code&&<div className="foundation-code-wrap"><header><Code2 size={15}/><span>Basic Java example</span></header><pre><code>{code}</code></pre></div>}</article>
      <article><span className="lesson-kicker">05 · CONCEPT</span><h3>Connection with algorithms</h3><p>Use this concept to justify conditions, loops, references, recursive calls, or stored states instead of treating code as isolated syntax.</p></article>
    </div>
    <div className="foundation-review-grid"><article className="foundation-mistakes"><span className="lesson-kicker">COMMON MISTAKES</span><h3>What to review</h3><ul>{mistakes.map(x=><li key={x}><AlertTriangle size={15}/><span>{x}</span></li>)}</ul></article><article className="foundation-checklist"><span className="lesson-kicker">APPLICATION GUIDE</span><h3>Steps for practice</h3><ol>{p[6].map(x=><li key={x}><CheckCircle2 size={15}/><span>{x}</span></li>)}</ol></article></div>
    <article className="complexity-summary-card foundation-summary-card"><Lightbulb size={20}/><div><span className="lesson-kicker">IDEA TO REMEMBER</span><p>{p[5]}</p></div></article>
  </section>;
}
